GET http://localhost:8080/

###

GET http://localhost:8080/5e8285489503673214ce2c92

###

POST http://localhost:8080/add
Content-Type: application/json

{
    "title": "test",
    "description": "test",
    "author": "V-boy"
}

###

PATCH http://localhost:8080/5e8285489503673214ce2c92
Content-Type: application/json

{
    "title": "Testing title!",
    "description":"testing 123",
    "author": "v-boy"
}
###

DELETE http://localhost:8080/5e8284cf1439570784971499
